# Generated by Django 4.1.6 on 2023-02-25 00:23

from django.db import migrations
from django.utils import timezone

import lorem
from random import shuffle, randint


def populate_db(apps, schema_editor):
    Blog = apps.get_model('blog', 'Blog')
    Comments = apps.get_model('blog', 'Comments')

    names = ['justin', 'erik', 'lincoln', 'isaac', 'liv', 'ashley', 'elaine', 'george', 'parmenio', 'yuxin', 'riot', 'jerry', 'ludwig', 'kaiser', 'emily', 'anne', 'leonidus']
    last_names = ['smith', 'lee', 'thompson', 'may', 'banner', 'stark', 'hawk', 'yamaguchi', 'chen', 'bulwark', 'herzog', 'jones', 'ruffner', 'young', 'kukahiko']

    for i in range(randint(5, 18)):
        # Adds a new Blog post
        b = Blog(title=lorem.sentence(),
                 author=names[randint(0, len(names)-1)] + ' ' + last_names[randint(0, len(last_names)-1)],
                 content=lorem.text(),
                 posted=timezone.now())
        b.save()

        # Add some comments to the Blog post
        for j in range(randint(2, 7)):
            commenter=names[randint(0, len(names)-1)] + ' ' + last_names[randint(0, len(last_names)-1)]
            Comments(blog=b,
                     commenter=commenter,
                     email= commenter + '@blarg.org',
                     content=lorem.paragraph(),
                     posted=timezone.now()).save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_db),
    ]
