# Generated by Django 4.1.6 on 2023-03-30 00:35

from django.db import migrations


def populate_unit_conversions(apps, schema_editor):

    unit_conversions = {'t_oz': 1.0, 'oz': 1.097, 'g': 31.1, 'kg': 0.0311, 'lb': 0.06857, 'T': 0.00003429}
    
    ConversionUnit = apps.get_model('unitconv', 'ConversionUnit')

    for key in unit_conversions:
        # Adds the conversions
        conv_unit = ConversionUnit(unit = key, conversion_factor = unit_conversions[key]).save()


class Migration(migrations.Migration):

    dependencies = [
        ('unitconv', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_unit_conversions),
    ]
