# Generated by Django 4.1.6 on 2023-03-16 10:26
# This file was created by running this command:
#   python3 manage.py makemigrations --empty arithmeticShootout --name populate


from django.db import migrations


def populate_operators(apps, schema_editor):

    operators = {'addition': '+', 'subtraction': '-', 'multiplication': '*', 'division': '/', 'remainder': '%', 'exponentiation': '**'}
    Operator = apps.get_model('arithmeticShootout', 'Operator')

    for key in operators:
        # Adds a new operator
        op = Operator(symbol = operators[key], name = key).save()
    

class Migration(migrations.Migration):

    dependencies = [
        ('arithmeticShootout', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_operators),
    ]

